# Default Parameters used in global_path_planner.cpp (server node that calculates optimal path)
# Node name is = amr_global_path_planner, executable name set in CMakeLists.txt is "global_path_planner"

amr_global_path_planner:
  ros__parameters:
    paths:
      map_path: "/ros2_ws/src/AMR-Logistic-System/laneletMaps/HS-SchmalkaldenPart1.osm"
      # debug_path will use the default if not specified
      # Uncomment and modify this line if you want to override the default debug path
      debug_path: "/ros2_ws/AMR/graph_debug"
      
    origins:
      # gps_origin is used to load the .OSM map. It doesnt have to be at exact center of the .OSM map
      gps_origin:
        latitude: 50.7153508
        longitude: 10.4680332
        altitude: 0.0

    bounding_box:
      # bBox GPS coords are used to validate the incoming GPS data (Start, End GPS should be within this bBox range) from client.
      # bBox range = constructed lanelet map range = AMR supported GPS range for Autonomous Nav. 
      min_lat: 50.7146143
      min_lon: 10.4612203
      max_lat: 50.7188432
      max_lon: 10.4691101

    # Threshold to determine Nearest AMR Navigable Lanelet or Area for path planning.
    max_distance_threshold: 20.0

    debug_options:
      # if "true", generated graph will be exported (graphml, graphviz, osm formats) and saved to "debug_path".
      export_built_graph: false

    log_data:
      log_path: "/ros2_ws/AMR/logs"
      log_file_type: "json" # json or log . ONly those 2 types of logs are supported
      log_level: 1 # 0: Debug, 1: Info, 2: Warning, 3: Error, 4: Fatal
