# Goal
float64[] goal_gps  # Goal GPS coordinates [latitude, longitude, altitude]
int64[] lanelet_ids      # Sequence of IDs (Lanelet or Area or Both) forming the Optimal path
bool[] is_inverted        # Boolean array indicating if the corresponding lanelet is inverted
float64 total_distance     # Estimated total distance of the path in meters
float64 estimated_time     # Estimated time to traverse the path in seconds
---
# Result
int32 status
string message
float64 total_distance  # Total distance The Robot traveled
float64 total_time      # Total time Robot took to reach goal
---
# Feedback 
float64 distance_remaining  # Estimated Remaining distance to goal
float64 estimated_time_remaining    # Estimated time remaining to reach goal