# central_management_params.yaml
amr_central_management:
  ros__parameters:
    # gps_origin is used to convert GPS data to UTM. It has to be the same origin used to load the .OSM map in Global Path Planner node.
    # for CO-ORDINATE TRANSFORMATION & MAP LOADING
    gps_origin:
      latitude: 50.7153508
      longitude: 10.4680332
      altitude: 0.0

      # time based path calculation is not yet implemented. Currently assuming Const Speed on all kinds of road.
      # For client request to "global_path_planner" server in "amr_global_path_planner" node
    use_time_based_routing: false